### ISSUE TITLE
Game lacks colorblind-friendly color scheme

### ISSUE THREAD

**Issue by danielhoherd** [James-Livesey/hexle#1]
For colorblind people, the interface of this game is difficult to navigate due to the color scheme. Same problem that Wodle has by default, except they have a colorblind friendly mode. I think their approach also has a problem though because by not having the default mode be colorblind-friendly, anybody who is colorblind cannot read the results that everybody else posts unless those people also turned their settings to be colorblind friendly. To that end I think that the game should have a colorblind friendly color scheme as the default.

**Comment by James-Livesey** [comment]
Thanks for the suggestion! I agree that the current colour scheme for Bytle lacks the sufficient colour contrast for colourblind users to discern between cells that are either correct or almost correct. This is definitely something that is needed to make Hexle playable for many who are colourblind.

As much as I agree that making the game colourblind-friendly as default would be more beneficial to colourblind users as a whole (especially with sharing), it could be confusing to users who don't use the colourblind-friendly mode and who are used to the default colour scheme for Wordle.

One approach I can immediately think of is to use the default colour scheme for Hexle, but incorporate a background pattern or icon to make it easier to determine the status of a cell — much like how MDN's browser support tables put an × behind the cells of their browser support table where browsers don't support a feature.

Sharing wise, again, switching out the cell emojis could be interesting (though I'm sure users would understand that if the bottom cells are the same colour, then that means that that colour means 'correct') — it would be great if the designers of emoji on various platforms made it easier to understand what colour a square emoji is! One alternative I can think of is to add a hyperlink into the textual content of the shared results that'll open up the Hexle game and fill in the results of the shared game (we'd need to hide the actual cell values, though!).

What's your thoughts? It's a bit of a compromise, but I feel that it should be a good solution that will make the game playable for colourblind users whilst not making the game look too different than the original Wordle game to those who are not colourblind.

**Comment by James-Livesey** [comment]
Colourblind simulation tests:

* Protanopia: hard to discern between green and yellow (both appear brown-yellow)
* Deuteranopia: hard to discern between green and yellow (both appear brown-yellow)
* Tritanopia: green and yellow can be discernible (yellow appears pink, green appears dark turquoise)
* Achromatopsia: hard to discern between green and yellow (both appear grey)

**Comment by James-Livesey** [comment]
Okay, so I've done the following on the `cb-friendly` branch:

* Added a button to toggle between default and colourblind-friendly colour schemes
* Added a link into the text that's copied when sharing a game which lets players see the result in the game itself (see screenshot below) so that users can see the game in their preferred colour scheme (stored in `localStorage`)

![Screenshot of shared game](https://user-images.githubusercontent.com/42580341/151659430-8d4ce9eb-eefe-4a1a-be78-eec8c2dd88d8.png)

If the user has set their colour scheme to be default and shares their game:

> #Hexle 0005 4/6
> 
> 🟩⬜⬜⬜
> 🟩🟨🟨🟨
> 🟩🟨🟩🟨
> 🟩🟩🟩🟩
> 
> http://jamesl.me/hexle?game=1bcb06f&n=5

If the user has set the colour scheme to be colourblind-friendly and shares their game:

> #Hexle 0005 4/6
> 
> 🟧⬜⬜⬜
> 🟧🟦🟦🟦
> 🟧🟦🟧🟦
> 🟧🟧🟧🟧
> 
> http://jamesl.me/hexle?game=1bcb06f&n=5

Will make a PR and merge it in! Let me know of any suggestions to improve upon the colourblind-friendliness of the game.

**Comment by danielhoherd** [comment]
Awesome! Thanks for handling it! It's much easier to grok now :)

#Hexle 0005 5/6

⬜⬜🟦⬜
⬜🟦⬜🟦
🟧⬜🟦⬜
🟧🟧⬜⬜
🟧🟧🟧🟧

https://jamesl.me/hexle/index.html?game=809691e&n=5

**Comment by James-Livesey** [comment]
Excellent! Thanks for providing feedback about how I can improve Hexle — contributions are always welcome!
