### ISSUE TITLE
b != b ?

### ISSUE THREAD

**Issue by notEthan** [James-Livesey/hexle#2]
played for the first time today. `b` was not yellow in the wrong position nor green in the right position.

<img src="https://user-images.githubusercontent.com/133719/151640145-2f97c40c-7edb-42b3-9bfe-e0964d6a9b43.png" width=440>

I opened an incognito window and put in the right answer, and that one recognized the `b` just fine, though.

<img src="https://user-images.githubusercontent.com/133719/151640301-4eb89000-398a-4ed4-8b0b-6a4c11ba3cc7.png" width=250>

on Chromium Version 97.0.4692.71 (Official Build) for Linux Mint (64-bit)

happy to debug on that browser window (still open) if you see this before it's closed.

**Comment by benjaminLevinson** [comment]
This same thing happened to me.

**Comment by James-Livesey** [comment]
Seemed to be a case mismatch bug (particularly on mobile) that I didn't catch yesterday because there were no digits A-F in yesterday's Hexle! I've published a fix to this bug, so hopefully after a refresh/cache clear, your Hexle answer should say it's correct now.
